name: deploy
on: push
permissions:
  pages: write
  id-token: write
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - run: |
          scripts/lint.sh
          scripts/build.sh
          for branch in $(curl https://api.github.com/repos/Lampadoforo/Enigma/branches | jq -r 'map(.name)[]'); do
            if [ ${branch} != ${{ github.ref_name }} ]; then
              mkdir "_site/${branch}/"
              wget -O "_site/${branch}/index.xhtml" "https://lampadoforo.github.io/Enigma/${branch}/"
              readonly logo=$(grep -Eo '[A-Za-z0-9\-_]{4}\.png' "_site/${branch}/index.xhtml")
              wget -P "_site/${branch}/" "https://lampadoforo.github.io/Enigma/${branch}/${logo}"
            fi
          done
          cp _site/main/* _site/
          sed 's/\/main//' _site/index.xhtml
      - uses: actions/upload-pages-artifact@v4
      - id: deployment
        uses: actions/deploy-pages@v5
